/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        RentalAgency agency = new RentalAgency();

        Vehicle car1 = new Car("car1", "Corvette", 50.0, true);
        Vehicle car2 = new Motocycle("moto22", "TA", 45.0);
        Vehicle car3 = new Motocycle("moto1", "Yamaha", 44);
        Vehicle car4 = new Truck("truck1", "MAN", 94);

        agency.addVehicle(car1);
        agency.addVehicle(car2);
        agency.addVehicle(car3);
        agency.addVehicle(car4);

        agency.seeVehicles();

        Customer customer1 = new Customer("Loica", 25);
        Customer customer2 = new Customer("Ben" , 83);
        Customer customer3 = new Customer("Janet" , 32);

        agency.rentVehicle("car1", customer1, 80);
        agency.rentVehicle("moto22", customer2, 77);
        agency.rentVehicle("truck1", customer3, 8);

        agency.seeTransactions();

        agency.bringVehicle("id1");

        agency.seeTransactions();
    }
}
